### ISSUE TITLE
Faulty Connection

### ISSUE THREAD

**Issue by bullishtq** [bitfocus/companion-module-toolsonair-justincapture#3]
EDIT: working with the current beta release

Connection for Tools on Air needs fixing or looking into. Adding connection on any PC/Mac, whether on the network or not always yields the same result displaying message: Warning - Error getting channel names. And then doesn't let you edit any IP information in the edit connection tab.

Image attached for reference.

Please suggest fix or workaround. Thanks!

Log info: Instance/Wrapper/justin: Error Getting Channel Names.

![Image](https://github.com/user-attachments/assets/e991490e-6f20-4df9-9468-8986f6508437)

**Comment by josephdadams** [comment]
Do you happen to know which version of the module you are running?

**Comment by bullishtq** [comment]
> Do you happen to know which version of the module you are running?

It’s the one included in stable release 3.4.3

It’s working on the beta I uninstalled the stable release.
